name: Go

on:
  push:
  pull_request:

jobs:
  integration_test:
    runs-on: ubuntu-latest
    services:
      ganache:
        image: 'Dockerfile'
        ports:
          - 8545

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Compile contract
      run: go run ./cmd/compile/

    - name: Test
      env:
        GANACHE_RPC_ENDPOINT: "http://localhost:8545"
      run: go test -v ./...
