name: Go

on:
  push:
  pull_request:

jobs:
  integration_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Compile contract
      run: go run ./cmd/compile/

    - name: Ganache server
      run: docker run -it -p 8545:8545 trufflesuite/ganache-cli:v6.12.2 -a 10 --seed 123 -b 0.3

    - name: Test
      env:
        GANACHE_RPC_ENDPOINT: "http://localhost:8545"
      run: go test -v ./...
